### DISCUSSION TITLE
Add support for a config file

### DISCUSSION THREAD

**Discussion by HexSleeves** [blue-build/.github#11] [General]
I think supporting a config file like `.bluebuild` or something similar could be beneficial in the future.

As our cli commands grows, users might have to enter more and more flags to get bluebuild to act how they intend, but having a config file to read from could save them from typing or using the same command over and over.

**Comment by xynydev** [comment]
I don't like the "`.bluebuild`" because it's a dotfile with an unspecified directory. I'm also not sure how the different commands would work if the config file was for setting args.

Maybe a flat `bluebuild.toml` file in each project directory like below could work.
```toml
# bluebuild.toml
[build]
arg1 = "value"
push = true
[generate]
output = "out.Containerfile"
```
`bluebuild build --config-file bluebuild.toml`

Or, I'm not sure why I thought of `toml` first, since we already also use `yaml`.
```yaml
build:
  arg1: value
  push: true
generate:
  output: out.Containerfile
```
`bluebuild generate --config-file bluebuild.yml`

Might also want different configs for the same thing, but not sure how that should be structured.
```yaml
commands:
   - name: build-ghcr
     type: build
     push: true
     registry-path: ghcr.io
   - name: build-gitlab
     type: build
     push: true
     registry-path: registry.gitlab.io
```
`bluebuild --commands-file bluebuild.yaml build-gitlab --recipe config/recipe-kde.yml`
