### DISCUSSION TITLE
rpm-ostree module - repo URL with the same name not supported?

### DISCUSSION THREAD

**Discussion by marcinjahn** [blue-build/.github#24] [Support] [answered]
I have the following `rpm-ostree` step:

```yaml
modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/varlad/zellij/repo/fedora-%OS_VERSION%/varlad-zellij-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://packages.microsoft.com/config/fedora/40/prod.repo
      - https://packages.microsoft.com/yumrepos/edge/config.repo
      - https://packages.microsoft.com/yumrepos/vscode/config.repo
      - https://downloads.k8slens.dev/rpm/lens.repo
    install:
      - fish
      - zellij
      - chromium
      - tailscale
      - podman-docker
      - docker-compose
      - microsoft-edge-stable
      - code
      - lens
```

Two repos have the same name of `.repo` resource:

- https://packages.microsoft.com/yumrepos/edge/config.repo
- https://packages.microsoft.com/yumrepos/vscode/config.repo

It seems like the build doesn't treat that well. In the logs I see:

```
#30 1.027 Saving '/etc/yum.repos.d//config.repo'
#30 1.027 HTTP response 200  [https://packages.microsoft.com/yumrepos/edge/config.repo]
#30 1.166 [0] Downloading 'https://packages.microsoft.com/yumrepos/vscode/config.repo' ...
#30 1.166 Saving '/etc/yum.repos.d//config.repo.1'
#30 1.166 HTTP response 200  [https://packages.microsoft.com/yumrepos/vscode/config.repo]
```

So, the ms-edge repo gets saved as `/etc/yum.repos.d//config.repo`.
And the vs-code one gets saved as '/etc/yum.repos.d//config.repo.1'.

Later on, I see that vs-code fails to be installed:

```
#30 1.184 Installing: fish zellij chromium tailscale podman-docker docker-compose microsoft-edge-stable code
#30 1.238 Enabled rpm-md repositories: edge-yum tailscale-stable copr:copr.fedorainfracloud.org:varlad:zellij packages-microsoft-com-prod rpmfusion-nonfree rpmfusion-nonfree-updates-testing rpmfusion-free rpmfusion-nonfree-updates copr:copr.fedorainfracloud.org:ublue-os:akmods rpmfusion-free-updates-testing rpmfusion-free-updates updates fedora-cisco-openh264 fedora updates-archive
#30 1.529 Updating metadata for 'edge-yum'...done
#30 1.864 Updating metadata for 'tailscale-stable'...done
#30 2.357 Updating metadata for 'copr:copr.fedorainfracloud.org:varlad:zellij'...done
#30 3.950 Updating metadata for 'packages-microsoft-com-prod'...done
#30 4.478 Updating metadata for 'rpmfusion-nonfree'...done
#30 5.792 Updating metadata for 'rpmfusion-nonfree-updates-testing'...done
#30 6.419 Updating metadata for 'rpmfusion-free'...done
#30 7.146 Updating metadata for 'rpmfusion-nonfree-updates'...done
#30 7.486 Updating metadata for 'copr:copr.fedorainfracloud.org:ublue-os:akmods'...done
#30 8.135 Updating metadata for 'rpmfusion-free-updates-testing'...done
#30 9.188 Updating metadata for 'rpmfusion-free-updates'...done
#30 15.75 Updating metadata for 'updates'...done
#30 16.18 Updating metadata for 'fedora-cisco-openh264'...done
#30 19.17 Updating metadata for 'fedora'...done
#30 19.82 Updating metadata for 'updates-archive'...done
#30 44.50 Importing rpm-md...done
#30 44.50 rpm-md repo 'edge-yum'; generated: 2024-05-07T17:40:01Z solvables: 98
#30 44.50 rpm-md repo 'tailscale-stable'; generated: 2024-05-08T21:42:52Z solvables: 99
#30 44.50 rpm-md repo 'copr:copr.fedorainfracloud.org:varlad:zellij'; generated: 2024-04-18T09:49:41Z solvables: 2
#30 44.50 rpm-md repo 'packages-microsoft-com-prod'; generated: 2024-04-23T16:08:53Z solvables: 24
#30 44.50 rpm-md repo 'rpmfusion-nonfree'; generated: 2024-04-20T12:18:23Z solvables: 194
#30 44.50 rpm-md repo 'rpmfusion-nonfree-updates-testing'; generated: 2024-05-08T12:18:39Z solvables: 6
#30 44.50 rpm-md repo 'rpmfusion-free'; generated: 2024-04-20T12:11:51Z solvables: 422
#30 44.50 rpm-md repo 'rpmfusion-nonfree-updates'; generated: 2024-05-08T12:18:33Z solvables: 54
#30 44.50 rpm-md repo 'copr:copr.fedorainfracloud.org:ublue-os:akmods'; generated: 2024-05-07T04:01:28Z solvables: 206
#30 44.50 rpm-md repo 'rpmfusion-free-updates-testing'; generated: 2024-05-08T11:59:01Z solvables: 15
#30 44.50 rpm-md repo 'rpmfusion-free-updates'; generated: 2024-05-08T11:58:16Z solvables: 72
#30 44.50 rpm-md repo 'updates'; generated: 2024-05-09T01:31:38Z solvables: 12139
#30 44.50 rpm-md repo 'fedora-cisco-openh264'; generated: 2023-12-11T14:43:50Z solvables: 4
#30 44.50 rpm-md repo 'fedora'; generated: 2024-04-14T18:51:11Z solvables: 74881
#30 44.50 rpm-md repo 'updates-archive'; generated: 2024-05-09T01:54:08Z solvables: 10617
#30 44.53 error: Packages not found: code
```

It seems that the vs-code repo was not even taken into account while downloading packages, probably due to that file name `config.repo.1`?

Is there anything I could do to fix it?
