### DISCUSSION TITLE
Fedora flatpaks - can I have it ?

### DISCUSSION THREAD

**Discussion by arturasb** [blue-build/.github#41] [Support] [answered]
Hi.

In the documentation on `default-flatpaks` it says that Fedora flatpak remote and flatpaks are removed by the `system-flatpak-setup`. Is it possible to prevent removal of Fedora's flatpak remote ? If not - is it possible to add that remote as a new flatpak remote ?
I need access to Fedora's flatpaks as I need `virt-manager` installed - I don't want to layer that and `virt-manager` is not available in Flathub ? The only source of `virt-manager` packaged as flatpak is Fedora's flatpak repo.

Regards
ArtūrasB.

**Comment by fiftydinar** [comment]
No for now.

Currently, it's hardcoded to remove them, including the repos. But maybe this can be added as a config option in recipe.

Like `fedora-flatpaks-removal`: `true/false` or something.

My advice is to wait for this implementation, but if you want to solve this now, follow below:

As a workaround, you can download [the current `default-flatpaks` module](https://github.com/blue-build/modules/tree/ca84ec87ebd4491cee8569fcb52326e74071f848/modules/default-flatpaks/v1), put that content in your image's repo `modules/default-flatpaks/` folder & exclude/comment the code here:

`system-flatpak-setup` (from line 24 to line 98):

https://github.com/blue-build/modules/blob/ca84ec87ebd4491cee8569fcb52326e74071f848/modules/default-flatpaks/v1/system-flatpak-setup#L24

`user-flatpak-setup` (from line 24 to line 85):

https://github.com/blue-build/modules/blob/ca84ec87ebd4491cee8569fcb52326e74071f848/modules/default-flatpaks/v1/user-flatpak-setup#L24

**Reply by arturasb** [reply]
> Like fedora-flatpaks-removal: true/false or something.

Maybe having a possibility to add Fedora's flatpak remote as a regular repo is better from abstraction perspective ?

**Reply by fiftydinar** [reply, marked as answer]
@arturasb

This should be resolved.
https://github.com/blue-build/modules/pull/359

Please tell if it works now.

Just add this to recipe.

``` yaml
repo-name: fedora
repo-url: oci+https://registry.fedoraproject.org
```

**Reply by arturasb** [reply]
The build was successful, but no flatpaks were installed - neither from Flathub nor from Fedora's repo. After system restart I see notification about flatpacks installed but there are no apps installed. I checked flatpak remotes - only this one is enabled:

```
Name         Options
flathub-user user

```
My repos are configured like this:

```
- type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    user:
      # Fedora flatpak repo because virt-manager is packaged as flatpak by Fedora
      repo-name: fedora
      repo-url: oci+https://registry.fedoraproject.org
      repo-title: "Fedora Flatpak (User)"
      install:
      - org.virt_manager.virt-manager

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
      remove:

    user:
      # repo-name will overwrite the previously-configured repo-name for the user remote
      repo-name: flathub-user
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-title: "Flathub (User)"
      install:
      - com.github.tchx84.Flatseal
      - de.haeckerfelix.Fragments
      - io.freetubeapp.FreeTube
      - org.keepassxc.KeePassXC
      - org.mozilla.Thunderbird
      - org.mozilla.firefox
      - org.telegram.desktop
      - org.libreoffice.LibreOffice
      - org.gnome.Connections
      - io.github.celluloid_player.Celluloid
      - com.usebottles.bottles
      - org.gnome.Boxes
      - com.mattjakeman.ExtensionManager
      - org.gnome.Connections
      - org.gnome.Calendar
      - org.gnome.Contacts
      - org.gnome.Geary
      - org.gnome.Calculator
      - org.gnome.TextEditor
      - org.fedoraproject.MediaWriter
      - org.gnome.Logs
      - com.github.wwmm.easyeffects
```
