### DISCUSSION TITLE
Limitations of our system

### DISCUSSION THREAD

**Discussion by xynydev** [blue-build/.github#5] [General]
...and how to tackle them?

I can think of one:
- Building two versions, say 38 and 39, of your image is hard.
  - Have to create two recipes and use a shared module file, so three files.
  - You ideally want the images to have the same name, right? `latest` wont be the latest version anymore, rather the image whose build completed later. The only way to solve this is two _differently named images_, which isn't nice.
  - Discussion continues at: https://github.com/blue-build/cli/issues/140

**Comment by gmpinder** [comment]
So we could support supplying an array into the version key in the recipe. Honestly wouldn't be too hard to add.

**Reply by xynydev** [reply]
Yeah, thought so too. Morning walk revelations. I'm just unsure, like, wouldn't the template command have to have two outputs then?

**Reply by gmpinder** [reply]
Yeah you're right, didn't think about that. Something to noodle on

**Comment by gerblesh** [comment]
I was thinking we could do something like this in a `recipe.yml` file:
```yaml
# image will be published to ghcr.io/<user>/<name>
name: template
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

image-tags:
    - latest
    - 39
```

keeping the recipe.yml files seperate makes sense because packages can be different between them, behavior, versioning, etc

```yaml
# image will be published to ghcr.io/<user>/<name>
name: template
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

image-tags:
    - gts
    - 38
```
