### DISCUSSION TITLE
how to change GRUB timeout?

### DISCUSSION THREAD

**Discussion by Bammede** [blue-build/.github#51] [Support]
How to change GRUB timeout, so it is different from the OS base image, but leave anything else untouched?

Latest Fedora uses: grub.cfg

**Comment by notnotno** [comment]
This is how I do it:

`sudo echo "set timeout=2" | sudo tee -a /boot/grub2/user.cfg`

**Reply by Bammede** [reply]
where do you put it in Bluebuild project?

**Reply by xynydev** [reply]
To run arbitrary lines of shell script you can use the `snippets` in the `script` module: https://blue-build.org/reference/modules/script/#example-configuration

```yaml
type: script
snippets:
  - "sudo echo "set timeout=2" | sudo tee -a /boot/grub2/user.cfg"
```
