### DISCUSSION TITLE
Image does not build

### DISCUSSION THREAD

**Discussion by MrQvest** [blue-build/.github#58] [Support] [answered]
TL;DR: Check your syntax. It was a dumb syntax mistake

I've been bashing my head against a wall for the last few days trying to make this work, as far as I can see, there are no syntax problems in any of my recipe files (I would also recommend checking the commit history to see what changed), but no matter what I try an error is found. You can find the image here: [https://github.com/MrQvest/my-atomic/](https://github.com/MrQvest/my-atomic/).

I also see this: 

```
help: Try adding these lines to the top of your file for editor validation
              highlights:
---
# yaml-language-server: $schema=https://schema.blue-build.org/module-v1.json

```
and after adding those, it still does not build with the same error: 
```
value is not valid under any of the schemas listed in the
      'anyOf' keyword
```

Would love some help on this, thank you for any answers

**Comment by gmpinder** [comment]
The issue is in `rpmfusion.yml`. You need to list all packages to install under `install.packages` and not have 2 sections of them.

You have:

```yaml
install:
  packages:
    - rpm-fusion-free-release-tainted

install:
  packages:
    - libdvdcss
 ```

Should be:

```yaml
install:
  packages:
    - rpm-fusion-free-release-tainted
    - libdvdcss
```
